### ISSUE TITLE
auth: The quota project is not set correctly, breaking clients

### ISSUE THREAD

**Issue by adamroyjones** [googleapis/google-cloud-go#10795]
## Client

Cloud Build, but I expect this generalises to almost everything.

## Environment

```
$ go version
go version go1.22.1 linux/amd64
```

## Code and Dependencies

The projects are fictive.

```go
package main

import (
	"context"
	"fmt"

	cloudbuildv2 "cloud.google.com/go/cloudbuild/apiv1/v2"
	"cloud.google.com/go/cloudbuild/apiv1/v2/cloudbuildpb"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
)

func main() {
	if err := run(); err != nil {
		panic(err)
	}
}

func run() error {
	const project = "A"
	const region = "europe-west1"

	ctx := context.Background()

	cli, err := cloudbuildv2.NewClient(ctx, option.WithQuotaProject(project))
	if err != nil {
		return err
	}

	it := cli.ListBuildTriggers(ctx, &cloudbuildpb.ListBuildTriggersRequest{
		Parent:    "projects/" + project + "/locations/" + region,
		ProjectId: project,
	})

	for {
		_, err := it.Next()
		if err == iterator.Done {
			return nil
		}
		if err != nil {
			return fmt.Errorf("could not list triggers: %w", err)
		}
	}
}
```

<details>
  <summary>go.mod</summary>

```text
module reprex

go 1.22.1

require (
	cloud.google.com/go/cloudbuild v1.17.0
	google.golang.org/api v0.195.0
)

require (
	cloud.google.com/go v0.115.1 // indirect
	cloud.google.com/go/auth v0.9.1 // indirect
	cloud.google.com/go/auth/oauth2adapt v0.2.4 // indirect
	cloud.google.com/go/compute/metadata v0.5.0 // indirect
	cloud.google.com/go/longrunning v0.5.12 // indirect
	github.com/felixge/httpsnoop v1.0.4 // indirect
	github.com/go-logr/logr v1.4.2 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
	github.com/google/s2a-go v0.1.8 // indirect
	github.com/googleapis/enterprise-certificate-proxy v0.3.2 // indirect
	github.com/googleapis/gax-go/v2 v2.13.0 // indirect
	go.opencensus.io v0.24.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.52.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.53.0 // indirect
	go.opentelemetry.io/otel v1.28.0 // indirect
	go.opentelemetry.io/otel/metric v1.28.0 // indirect
	go.opentelemetry.io/otel/trace v1.28.0 // indirect
	golang.org/x/crypto v0.26.0 // indirect
	golang.org/x/net v0.28.0 // indirect
	golang.org/x/oauth2 v0.22.0 // indirect
	golang.org/x/sync v0.8.0 // indirect
	golang.org/x/sys v0.24.0 // indirect
	golang.org/x/text v0.17.0 // indirect
	golang.org/x/time v0.6.0 // indirect
	google.golang.org/genproto/googleapis/api v0.0.0-20240814211410-ddb44dafa142 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240823204242-4ba0660f739c // indirect
	google.golang.org/grpc v1.65.0 // indirect
	google.golang.org/protobuf v1.34.2 // indirect
)
```

</details>

## Expected behavior

I expected to be able to list build triggers in a project that supports Cloud Build.

## Actual behavior

I cannot, as the quota project ID is set to a project that does not support Cloud Build.

### Practical summary

We have:

- two example projects, one that has Cloud Build enabled (A) and another that doesn't (B);
- a program that queries Cloud Build in project A; and
- application default credentials that set the quota project to B.

Even when the cilent library is constructed with 

```go
option.WithQuotaProject("A")
```

and even if

```sh
GOOGLE_CLOUD_QUOTA_PROJECT=A
```

is set, the quota project is set to the value of `quota_project_id` in the application default credentials: B.

This leads queries of Cloud Build in A to fail.

### Technical details

There are (at least) three ways that the quota project can be set with the Cloud Build client library.

Firstly, it can be set with a client option.

```go
cli, err := cloudbuildv2.NewClient(ctx, option.WithQuotaProject("my-gcp-project"))
if err != nil {
	return err
}
```

Secondly, it can be set with an environment variable.

```sh
GOOGLE_CLOUD_QUOTA_PROJECT=my-gcp-project
```

Thirdly, it can be inferred from the application default credentials.

```
$ cat ~/.config/gcloud/application_default_credentials.json | grep quota
  "quota-project-id": "my-gcp-project"
```

The [intended precedence](https://github.com/googleapis/google-api-go-client/blob/21f10edb1d9d6a3d3baa5b1edcef6588da99def8/internal/creds.go#L242-L261), as of commit 21f10edb1d9d6a3d3baa5b1edcef6588da99def8, appears to be:

```go
// GetQuotaProject retrieves quota project with precedence being: client option,
// environment variable, creds file.
```

I've observed that sometimes the credentials file takes precedence over the others. It is specifically from the new auth library: if I vendor the code and insert a panic in cloud.google.com/go/auth.NewCredentials that prints out the value of opts.QuotaProjectIDProvider, I see the ADC value, and not the value of the environment variable or the client option. When doing this, the stack trace looks as follows:

```
goroutine 1 [running]:
cloud.google.com/go/auth.NewCredentials(...)
	/home/adamjones/tmp/reprex/vendor/cloud.google.com/go/auth/auth.go:227
cloud.google.com/go/auth/credentials.fileCredentials({0xc000394000, 0x18c, 0x200}, 0xc000000840)
	/home/adamjones/tmp/reprex/vendor/cloud.google.com/go/auth/credentials/filetypes.go:107 +0x4c5
cloud.google.com/go/auth/credentials.readCredentialsFileJSON({0xc000394000, 0x18c, 0x200}, 0xc000000840)
	/home/adamjones/tmp/reprex/vendor/cloud.google.com/go/auth/credentials/detect.go:220 +0xb3
cloud.google.com/go/auth/credentials.DetectDefault(0xc000000840)
	/home/adamjones/tmp/reprex/vendor/cloud.google.com/go/auth/credentials/detect.go:95 +0x212
cloud.google.com/go/auth/grpctransport.dial({0xc89080, 0x11ba160}, 0x1, 0xc000196c00)
	/home/adamjones/tmp/reprex/vendor/cloud.google.com/go/auth/grpctransport/grpctransport.go:260 +0x2ca
cloud.google.com/go/auth/grpctransport.Dial({0xc89080, 0x11ba160}, 0x1, 0xc000196c00)
	/home/adamjones/tmp/reprex/vendor/cloud.google.com/go/auth/grpctransport/grpctransport.go:191 +0x15c
google.golang.org/api/transport/grpc.dialPoolNewAuth({0xc89080, 0x11ba160}, 0x1, 0x0, 0xc0003383c0)
	/home/adamjones/tmp/reprex/vendor/google.golang.org/api/transport/grpc/dial.go:224 +0x6ea
google.golang.org/api/transport/grpc.DialPool({0xc89080, 0x11ba160}, {0xc000190e10?, 0xc0002f5510?, 0xc0002eff40?})
	/home/adamjones/tmp/reprex/vendor/google.golang.org/api/transport/grpc/dial.go:141 +0x119
cloud.google.com/go/cloudbuild/apiv1/v2.NewClient({0xc89080, 0x11ba160}, {0x0, 0x0, 0x100470800?})
	/home/adamjones/tmp/reprex/vendor/cloud.google.com/go/cloudbuild/apiv1/v2/cloud_build_client.go:644 +0x1c5
main.run()
	/home/adamjones/tmp/reprex/main.go:24 +0x2c
main.main()
	/home/adamjones/tmp/reprex/main.go:13 +0x13
exit status 2
```

Ordinarily I'd offer a pull request, but this is so deep in the code and the ramifications are so potentially disastrous that... rather you than me!

Please let me know if you need any more details.

**Comment by codyoss** [comment]
If you upgrade to `cloud.google.com/goauth@v0.9.2` this should be fixed. Thank you for the report!

**Comment by adamroyjones** [comment]
Thanks for the quick fix!
