### ISSUE TITLE
pubsub: unflake pstest's TestMultiStreams

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1191]
```
$ cd pubsub/pstest
$ go test . -v -race -cpu 1,4 -count 10000 -run TestMultiStreams
[...]
=== RUN   TestMultiStreams
--- PASS: TestMultiStreams (0.04s)
=== RUN   TestMultiStreams
--- PASS: TestMultiStreams (0.03s)
=== RUN   TestMultiStreams

--- FAIL: TestMultiStreams (10.04s)
    fake_test.go:504: {map[string]*pubsub.PubsubMessage}["m3"]:
        	-: <non-existent>
        	+: s`data:"d4" message_id:"m3" publish_time:<seconds:1540218148 nanos:790632000 > `
```

**Comment by odeke-em** [comment]
I just encountered this and now a crash at https://source.cloud.google.com/results/invocations/6b100306-6b79-4c62-972a-321fe1fe6e2f/targets/cloud-go-libraries%2Fgoogle-cloud-go%2Fpresubmit%2Fgo110/log

```shell
--- FAIL: TestMultiStreams (5.02s)
	fake_test.go:548: timed out waiting for stream 1 to receive any message
=== RUN   TestStreamingPullTimeout
panic: Fail in goroutine after TestMultiStreams has completed
goroutine 238 [running]:
testing.(*common).Fail(0xc42032a3c0)
	/usr/local/go/src/testing/testing.go:509 +0x1ba
testing.(*common).Error(0xc42032a3c0, 0xc420539fa0, 0x1, 0x1)
	/usr/local/go/src/testing/testing.go:579 +0x7d
cloud.google.com/go/pubsub/pstest.TestMultiStreams.func2(0xc41260, 0xc42021ea40, 0xc42032a3c0, 0xc4203296e0)
	/root/go/src/cloud.google.com/go/pubsub/pstest/fake_test.go:530 +0xb4
created by cloud.google.com/go/pubsub/pstest.TestMultiStreams
	/root/go/src/cloud.google.com/go/pubsub/pstest/fake_test.go:527 +0x54e
FAIL	cloud.google.com/go/pubsub/pstest	12.865s
```

**Comment by jadekler** [comment]
Another occurrence https://sponge.corp.google.com/target?id=f822a1db-91ad-407a-b1d2-e5ef34a682b9&target=cloud-go-libraries/google-cloud-go/presubmit/go113&searchFor=&show=ALL&sortBy=STATUS

**Comment by codyoss** [comment]
Looks like this was solved via https://code-review.googlesource.com/c/34870
