### ISSUE TITLE
pubsub: Hanging when calling CreateTopic

### ISSUE THREAD

**Issue by fastest963** [googleapis/google-cloud-go#1449]
## Client

PubSub c8433c9 (same on working and broken)

## Dep versions (working)

google.golang.org/grpc (git) - 532a0b9 only force update picker when cache is used (sub-balancer is round-robin) (#2843)
google.golang.org/api (git) - 2289773 all: autogenerated update (2019-06-04)

## Dep versions (broken)

google.golang.org/grpc (git) - 2df9cb8 xds: rpc counts (start/end) per locality (#2805)
google.golang.org/api (git) - 321c6e0 transport/grpc: add support for GCP direct path

## Describe Your Environment

Compute Engine running CentOS7 and golang 1.12.5

## Expected Behavior

When we call CreateTopic it usually returns fairly quickly.

## Actual Behavior

Hangs for 10+ seconds. This is causing our application to crash on startup since we only give the application 10 seconds to startup before killing it and trying to start it again.

Here's a stack trace:
```
goroutine 1 [select]:
github.com/googleapis/gax-go/v2.Sleep(0x111ba40, 0xc000571b90, 0xb536d772, 0xb536d772, 0xffffffffffffff01)
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/github.com/googleapis/gax-go/v2/invoke.go:55 +0xd2
github.com/googleapis/gax-go/v2.invoke(0x111ba40, 0xc000571b90, 0xc000918ce0, 0xf7a4a8, 0x0, 0x0, 0x0, 0xf7b4a0, 0x40c368, 0x20)
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/github.com/googleapis/gax-go/v2/invoke.go:95 +0x16e
github.com/googleapis/gax-go/v2.Invoke(0x111ba40, 0xc000571b90, 0xc000918ce0, 0xc001385b20, 0x1, 0x1, 0x0, 0x0)
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/github.com/googleapis/gax-go/v2/invoke.go:48 +0xf6
cloud.google.com/go/pubsub/apiv1.(*PublisherClient).CreateTopic(0xc000571980, 0x111ba40, 0xc000571b90, 0xc000426e10, 0x0, 0x0, 0x0, 0x191b548, 0xc00051cae0, 0x30)
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/cloud.google.com/go/pubsub/apiv1/publisher_client.go:173 +0x2db
cloud.google.com/go/pubsub.(*Client).CreateTopic(0xc000918ca0, 0x111b9c0, 0xc00003e078, 0xc00051cae0, 0x30, 0xc0014b7900, 0xc6228c, 0x0)
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/cloud.google.com/go/pubsub/topic.go:103 +0xc5
bitbucket.org/levenlabs/llib/ldb.(*PubSub).createTopic(0xc000367e30, 0x111b9c0, 0xc00003e078, 0xc00051cae0, 0x30, 0xc00051cae0, 0x30, 0x0)
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/bitbucket.org/levenlabs/llib/ldb/pubsub.go:289 +0x6a
bitbucket.org/levenlabs/llib/ldb.(*PubSub).CreateTopic(0xc000367e30, 0x111b9c0, 0xc00003e078, 0xc00051cae0, 0x30, 0x0, 0x0, 0x0, 0x1100be0, 0xc000061500)
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/bitbucket.org/levenlabs/llib/ldb/pubsub.go:309 +0xb2
gerrit.levenlabs.com/go-cron.Configure.func1()
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/gerrit.levenlabs.com/go-cron/cron.go:147 +0x161
bitbucket.org/levenlabs/llib/lflag.Parse(0x1101a00, 0xc0003d11e0)
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/bitbucket.org/levenlabs/llib/lflag/lflag.go:423 +0x58e
bitbucket.org/levenlabs/llib/lflag.Configure()
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/bitbucket.org/levenlabs/llib/lflag/lflag.go:440 +0x113
main.main()
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/gerrit.levenlabs.com/visitor-api/cmd/visitor-api-consumer/worker.go:56 +0x289
goroutine 34 [IO wait]:
internal/poll.runtime_pollWait(0x7f44bd2a1d68, 0x72, 0xffffffffffffffff)
/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000b5498, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000b5480, 0xc000432000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000b5480, 0xc000432000, 0x1000, 0x1000, 0xc00047b4a0, 0xc0003decc0, 0xc000096dd0)
/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e5d8, 0xc000432000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/net/net.go:177 +0x69
net/http.(*persistConn).Read(0xc000414d80, 0xc000432000, 0x1000, 0x1000, 0x459e80, 0xc000096e88, 0x2)
/usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc0003df2c0)
/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc0003df2c0, 0x1, 0x2, 0x0, 0x0, 0xc00047b400, 0x0)
/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc000414d80)
/usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
/usr/local/go/src/net/http/transport.go:1357 +0xae8
goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc000414d80)
/usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
/usr/local/go/src/net/http/transport.go:1358 +0xb0d
goroutine 47 [select]:
net/http.(*persistConn).writeLoop(0xc000415320)
/usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
/usr/local/go/src/net/http/transport.go:1358 +0xb0d
goroutine 48 [select]:
google.golang.org/grpc/resolver/dns.(*dnsResolver).watcher(0xc000365cb0)
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/google.golang.org/grpc/resolver/dns/dns_resolver.go:270 +0x2fb
created by google.golang.org/grpc/resolver/dns.(*dnsBuilder).Build
/opt/TeamCityBuild/work/wombat-2/a2b63c274600917b/.deps/src/google.golang.org/grpc/resolver/dns/dns_resolver.go:152 +0x502
goroutine 46 [IO wait]:
internal/poll.runtime_pollWait(0x7f44bd2a1e38, 0x72, 0xffffffffffffffff)
/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000b5b98, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000b5b80, 0xc000472000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000b5b80, 0xc000472000, 0x1000, 0x1000, 0x1, 0x42f4dc, 0xc000098b88)
/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e688, 0xc000472000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/net/net.go:177 +0x69
net/http.(*persistConn).Read(0xc000415320, 0xc000472000, 0x1000, 0x1000, 0xc000098c88, 0x404de5, 0xc000081da0)
/usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc0003dfe00)
/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc0003dfe00, 0x1, 0x0, 0x0, 0x1, 0xc000080e00, 0x0)
/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc000415320)
/usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
/usr/local/go/src/net/http/transport.go:1357 +0xae8
```

I don't think the issue is with this package but I'm not sure given the changes in `google.golang.org/api` and if there's something here that needs to change to compensate.

**Comment by jadekler** [comment]
cc @kamalaboulhosn in case this is some service slowdown (we've not had any bugs around CreateTopic / etc lately).

**Comment by fastest963** [comment]
I should clarify that rolling back to the "working" version fixed the issue and it started returning from CreateTopic quickly again.

**Comment by jadekler** [comment]
OH. Definitely something on our end then. Sorry I missed that.

**Comment by hongalex** [comment]
So I spun up a GCE instance with CentOS7 to try and reproduce your issue, but it doesn't seem to be taking more than 500ms to call `CreateTopic`. Can you pull the latest commits for `google.golang.org/grpc` to see if that changes anything?

**Comment by fastest963** [comment]
Interesting. I tried the latest:
```
google.golang.org/api (git) - 321c6e0 transport/grpc: add support for GCP direct path
google.golang.org/grpc (git) - d33cecd xds: fix difference between user target name and resource name (#2845)
```
and I'm still getting the issue. But when I reverted the `google.golang.org/api` change the problem disappeared. To clarify, I reverted it back to:
```
google.golang.org/api (git) - 2289773 all: autogenerated update (2019-06-04)
```

**Comment by fastest963** [comment]
Actually it seems like:
```
golang.org/x/oauth2 (git) - 0f29369 google: add some metadata to GCE tokens to identify the token's source
```
In combination with the `google.golang.org/api` change seem to cause the issue.

Here's a reproduction script:
```
package main

import (
	"context"
	"flag"
	"fmt"
	_ "net/http/pprof"

	"cloud.google.com/go/pubsub"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func isGoogleCloudErrAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	s, ok := status.FromError(err)
	return ok && s.Code() == codes.AlreadyExists
}

func main() {
	proj := flag.String("project", "", "project name")
	topic := flag.String("topic", "pubsub_test", "name of the topic to use")
	flag.Parse()

	psc, err := pubsub.NewClient(context.Background(), *proj)
	if err != nil {
		panic(err)
	}
	t, err := psc.CreateTopic(context.Background(), *topic)
	if err != nil && !isGoogleCloudErrAlreadyExists(err) {
		panic(err)
	} else if t == nil {
		fmt.Println("created")
	}
}
```

**Comment by fastest963** [comment]
Here's a fix for the issue with `google.golang.org/api`: https://code-review.googlesource.com/c/google-api-go-client/+/41670

**Comment by jadekler** [comment]
Wow. _Great_ spot. Submitted.

**Comment by jadekler** [comment]
@fastest963 Could you confirm the problem is resolved with your CL submitted? (that is, can we close this issue?)

We'll push out a release to include that change by EOW.

**Comment by fastest963** [comment]
@jadekler sorry for the delay, we ran into a different issue when we deployed by fix caused by ad9d9cbfd8a5e1a022fe6f4ba329c01798b03217. We weren't setting `BufferedByteLimit` before since it didn't exist and so all of our publishes are failing with `bundler reached buffered byte limit` presumably because it's 0. There should be a default in there or something warning people that they need to set it when they previously didn't.

**Comment by jadekler** [comment]
@fastest963 https://code-review.googlesource.com/c/gocloud/+/41692

**Comment by fastest963** [comment]
Thanks for that! I can confirm that everything is working on our end. Thanks again

**Comment by jadekler** [comment]
Right on - thanks for reporting.
