### ISSUE TITLE
pubsub: fix test data race

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1487]
https://sponge.corp.google.com/target?id=aa4dda14-f852-47f6-9965-72da0b65f934&target=cloud-go-libraries/google-cloud-go/continuous/go112&searchFor=&show=FAILED&sortBy=STATUS

```
=== RUN   TestEndToEnd_LongProcessingTime
2019/07/03 05:11:25 quiesced
--- PASS: TestEndToEnd_LongProcessingTime (148.61s)
    endtoend_test.go:266: 0: start receive
==================
WARNING: DATA RACE
Read at 0x00c000292043 by goroutine 190:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:629 +0x132
  testing.(*common).Logf()
      /usr/local/go/src/testing/testing.go:614 +0x90
  cloud.google.com/go/pubsub/internal/longtest.(*consumer).consume()
      /root/go/src/cloud.google.com/go/pubsub/internal/longtest/endtoend_test.go:269 +0x3e1

Previous write at 0x00c000292043 by main goroutine:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:856 +0x354
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:869 +0x17f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:44 +0x222

Goroutine 190 (running) created at:
  cloud.google.com/go/pubsub/internal/longtest.TestEndToEnd_LongProcessingTime()
      /root/go/src/cloud.google.com/go/pubsub/internal/longtest/endtoend_test.go:179 +0x707
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
==================
panic: Log in goroutine after TestEndToEnd_LongProcessingTime has completed

goroutine 40312 [running]:
testing.(*common).logDepth(0xc000292200, 0xc0002c2cc0, 0x19, 0x3)
	/usr/local/go/src/testing/testing.go:634 +0x51a
testing.(*common).log(...)
	/usr/local/go/src/testing/testing.go:614
testing.(*common).Logf(0xc000292200, 0xcf6781, 0x18, 0xc00022ff88, 0x2, 0x2)
	/usr/local/go/src/testing/testing.go:649 +0x91
cloud.google.com/go/pubsub/internal/longtest.(*consumer).consume(0xc000020e40, 0xddf7a0, 0xc000616060, 0xc000292200, 0xc000612410)
	/root/go/src/cloud.google.com/go/pubsub/internal/longtest/endtoend_test.go:269 +0x3e2
created by cloud.google.com/go/pubsub/internal/longtest.TestEndToEnd_LongProcessingTime
	/root/go/src/cloud.google.com/go/pubsub/internal/longtest/endtoend_test.go:179 +0x708
FAIL	cloud.google.com/go/pubsub/internal/longtest	773.088s
```

**Comment by hongalex** [comment]
I believe this was resolved by https://code-review.googlesource.com/c/gocloud/+/42811, since I can't seem to reproduce anymore.

**Comment by jadekler** [comment]
Oh right, thanks!
