### ISSUE TITLE
Unflake TestIntegration_Objects

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1583]
https://sponge.corp.google.com/target?id=cc925661-24fe-478f-9aee-3b1ec21d3305&target=cloud-go-libraries/google-cloud-go/continuous/go110&searchFor=&show=ALL&sortBy=STATUS

https://source.cloud.google.com/results/invocations/cc925661-24fe-478f-9aee-3b1ec21d3305

```
=== RUN   TestIntegration_Objects
--- FAIL: TestIntegration_Objects (1.05s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 152 [running]:
testing.tRunner.func1(0xc42015c3c0)
	/usr/local/go/src/testing/testing.go:742 +0x567
panic(0xcf8100, 0x11efba0)
	/usr/local/go/src/runtime/panic.go:502 +0x24a
cloud.google.com/go/storage.(*ObjectIterator).Next(0xc4201404d0, 0x16, 0x3600000000ce2c01, 0xce2cc0)
	/root/go/src/cloud.google.com/go/storage/bucket.go:1093 +0x16b
cloud.google.com/go/storage.testObjectIterator.func2(0xd09400, 0xc4201404d0, 0x16, 0xce2cc0, 0x0, 0xc420330790)
	/root/go/src/cloud.google.com/go/storage/integration_test.go:942 +0x4e
google.golang.org/api/iterator/testing.testNext(0xca1300, 0xc4203307a0, 0x97, 0xd09400, 0xc4201404d0, 0xdf7710, 0x46e815, 0x7f11aded26c8, 0x0)
	/root/go/src/google.golang.org/api/iterator/testing/testing.go:86 +0x546
google.golang.org/api/iterator/testing.TestIterator(0xca1300, 0xc4203307a0, 0xc420191df8, 0xdf7710, 0x3, 0xc420330780, 0x2)
	/root/go/src/google.golang.org/api/iterator/testing/testing.go:60 +0xf2
cloud.google.com/go/storage.testObjectIterator(0xc42015c3c0, 0xc4200c1810, 0xc4202bc780, 0x3, 0x3)
	/root/go/src/cloud.google.com/go/storage/integration_test.go:940 +0x643
cloud.google.com/go/storage.TestIntegration_Objects(0xc42015c3c0)
	/root/go/src/cloud.google.com/go/storage/integration_test.go:546 +0xaf5
testing.tRunner(0xc42015c3c0, 0xdf7538)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565
```

**Comment by odeke-em** [comment]
Thank you for reporting this @jadekler! It is a legitimate failure due to an oversight in the length/size calculation in the size for (*storage.ObjectIterator). I've mailed https://code-review.googlesource.com/c/gocloud/+/45673
