### ISSUE TITLE
internal: MediaInfo.UploadRequest possible goroutines leaking

### ISSUE THREAD

**Issue by rntk** [googleapis/google-cloud-go#1651]
Function UploadRequest (https://github.com/googleapis/google-api-go-client/blob/v0.13.0/internal/gensupport/media.go#L273) return function GetBody.

GetBody, by combineBodyMedia, call function newMultipartReader (https://github.com/googleapis/google-api-go-client/blob/v0.13.0/internal/gensupport/media.go#L120).

newMultipartReader use io.Pipe to create new io.Reader and create new goroutine to provide data for pipe (https://github.com/googleapis/google-api-go-client/blob/v0.13.0/internal/gensupport/media.go#L131).

From https://golang.org/pkg/io/#Pipe
> each Write to the PipeWriter blocks until it has satisfied one or more Reads from the PipeReader that fully consume the written data.

If we call GetBody and do not consume data from Reader we got "forever" blocked goroutine on (https://github.com/googleapis/google-api-go-client/blob/v0.13.0/internal/gensupport/media.go#L131).

In particular, this lead to goroutines and memory leaking in storage client. In one of long running processes (about 7 days) got leaked:  62 goroutines and 496Mb of memory.

Example of debug stack trace:

```
2019/11/04 10:41:32 Start getBody
goroutine 2441 [running]:
runtime/debug.Stack(0x50c09c, 0xc0000ae000, 0x2)
	/opt/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/opt/go/src/runtime/debug/stack.go:16 +0x22
google.golang.org/api/internal/gensupport.(*MediaInfo).UploadRequest.func2(0xa4b760, 0xc0003da300, 0xf0ef40, 0x7fe2a9795000)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/internal/gensupport/media.go:298 +0xbc
net/http.(*Transport).roundTrip(0xee7d80, 0xc0003da200, 0x964d80, 0xee7b01, 0xc00011f4a0)
	/opt/go/src/net/http/transport.go:556 +0x760
net/http.(*Transport).RoundTrip(0xee7d80, 0xc0003da200, 0xa5f8f9, 0xa, 0xc00011f528)
	/opt/go/src/net/http/roundtrip.go:17 +0x35
google.golang.org/api/transport/http.parameterTransport.RoundTrip(0xa6b827, 0x1e, 0x0, 0x0, 0x0, 0x0, 0xb1fca0, 0xee7d80, 0xc0003da100, 0xa67ced, ...)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/transport/http/dial.go:151 +0x329
go.opencensus.io/plugin/ochttp.(*traceTransport).RoundTrip(0xc000d0e580, 0xc0003da100, 0xc00000e360, 0x1, 0x1)
	/home/dev/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/trace.go:84 +0x456
go.opencensus.io/plugin/ochttp.statsTransport.RoundTrip(0xb1f340, 0xc000d0e580, 0xc000279f00, 0xc001330e40, 0xc001330e40, 0x9d3be0)
	/home/dev/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/client_stats.go:57 +0x5cc
go.opencensus.io/plugin/ochttp.(*Transport).RoundTrip(0xc0001241e0, 0xc000279f00, 0xc000279f00, 0x0, 0x150)
	/home/dev/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/client.go:99 +0x20e
golang.org/x/oauth2.(*Transport).RoundTrip(0xc0000eaab0, 0xc000279e00, 0x0, 0x0, 0x0)
	/home/dev/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45/transport.go:56 +0x124
net/http.send(0xc000279e00, 0xb1f3e0, 0xc0000eaab0, 0x0, 0x0, 0x0, 0xc0000104e0, 0xc001323ae0, 0x1, 0x0)
	/opt/go/src/net/http/client.go:250 +0x43a
net/http.(*Client).send(0xc0000eaae0, 0xc000279e00, 0x0, 0x0, 0x0, 0xc0000104e0, 0x0, 0x1, 0xc000129848)
	/opt/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc0000eaae0, 0xc000279e00, 0x0, 0x0, 0x0)
	/opt/go/src/net/http/client.go:641 +0x3ce
net/http.(*Client).Do(...)
	/opt/go/src/net/http/client.go:509
google.golang.org/api/internal/gensupport.send(0xb2ad20, 0xc00009e020, 0xc0000eaae0, 0xc000279d00, 0xf103a0, 0x0, 0xc0001299a8)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/internal/gensupport/send.go:72 +0x106
google.golang.org/api/internal/gensupport.SendRequest(0xb2ad20, 0xc00009e020, 0xc0000eaae0, 0xc000279d00, 0xc000129c98, 0x79, 0x7fe2a97da198)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/internal/gensupport/send.go:57 +0x19c
google.golang.org/api/storage/v1.(*ObjectsInsertCall).doRequest(0xc000125a40, 0xa5b0d9, 0x4, 0x0, 0x0, 0x0)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/storage/v1/storage-gen.go:10041 +0x8d1
google.golang.org/api/storage/v1.(*ObjectsInsertCall).Do(0xc000125a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/storage/v1/storage-gen.go:10053 +0xa8
cloud.google.com/go/storage.(*Writer).open.func1(0xc0000bcfc0, 0xc000220540, 0xc0000104b0, 0xc001330ce0, 0x1, 0x1)
	/home/dev/go/pkg/mod/cloud.google.com/go/storage@v1.1.2/writer.go:160 +0x77a
created by cloud.google.com/go/storage.(*Writer).open
	/home/dev/go/pkg/mod/cloud.google.com/go/storage@v1.1.2/writer.go:110 +0x3f3

2019/11/04 10:41:33 Start getBody
goroutine 2441 [running]:
runtime/debug.Stack(0x50c09c, 0xc0000ae000, 0x2)
	/opt/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/opt/go/src/runtime/debug/stack.go:16 +0x22
google.golang.org/api/internal/gensupport.(*MediaInfo).UploadRequest.func2(0xa4b760, 0xc0003da400, 0xf0ef40, 0x7fe2a9795000)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/internal/gensupport/media.go:298 +0xbc
net/http.(*Transport).roundTrip(0xee7d80, 0xc0003da200, 0x964d80, 0xee7b01, 0xc00011f4a0)
	/opt/go/src/net/http/transport.go:556 +0x760
net/http.(*Transport).RoundTrip(0xee7d80, 0xc0003da200, 0xa5f8f9, 0xa, 0xc00011f528)
	/opt/go/src/net/http/roundtrip.go:17 +0x35
google.golang.org/api/transport/http.parameterTransport.RoundTrip(0xa6b827, 0x1e, 0x0, 0x0, 0x0, 0x0, 0xb1fca0, 0xee7d80, 0xc0003da100, 0xa67ced, ...)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/transport/http/dial.go:151 +0x329
go.opencensus.io/plugin/ochttp.(*traceTransport).RoundTrip(0xc000d0e580, 0xc0003da100, 0xc00000e360, 0x1, 0x1)
	/home/dev/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/trace.go:84 +0x456
go.opencensus.io/plugin/ochttp.statsTransport.RoundTrip(0xb1f340, 0xc000d0e580, 0xc000279f00, 0xc001330e40, 0xc001330e40, 0x9d3be0)
	/home/dev/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/client_stats.go:57 +0x5cc
go.opencensus.io/plugin/ochttp.(*Transport).RoundTrip(0xc0001241e0, 0xc000279f00, 0xc000279f00, 0x0, 0x150)
	/home/dev/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/client.go:99 +0x20e
golang.org/x/oauth2.(*Transport).RoundTrip(0xc0000eaab0, 0xc000279e00, 0x0, 0x0, 0x0)
	/home/dev/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45/transport.go:56 +0x124
net/http.send(0xc000279e00, 0xb1f3e0, 0xc0000eaab0, 0x0, 0x0, 0x0, 0xc0000104e0, 0xc001323ae0, 0x1, 0x0)
	/opt/go/src/net/http/client.go:250 +0x43a
net/http.(*Client).send(0xc0000eaae0, 0xc000279e00, 0x0, 0x0, 0x0, 0xc0000104e0, 0x0, 0x1, 0xc000129848)
	/opt/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc0000eaae0, 0xc000279e00, 0x0, 0x0, 0x0)
	/opt/go/src/net/http/client.go:641 +0x3ce
net/http.(*Client).Do(...)
	/opt/go/src/net/http/client.go:509
google.golang.org/api/internal/gensupport.send(0xb2ad20, 0xc00009e020, 0xc0000eaae0, 0xc000279d00, 0xf103a0, 0x0, 0xc0001299a8)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/internal/gensupport/send.go:72 +0x106
google.golang.org/api/internal/gensupport.SendRequest(0xb2ad20, 0xc00009e020, 0xc0000eaae0, 0xc000279d00, 0xc000129c98, 0x79, 0x7fe2a97da198)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/internal/gensupport/send.go:57 +0x19c
google.golang.org/api/storage/v1.(*ObjectsInsertCall).doRequest(0xc000125a40, 0xa5b0d9, 0x4, 0x0, 0x0, 0x0)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/storage/v1/storage-gen.go:10041 +0x8d1
google.golang.org/api/storage/v1.(*ObjectsInsertCall).Do(0xc000125a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/dev/go/pkg/mod/google.golang.org/api@v0.11.0/storage/v1/storage-gen.go:10053 +0xa8
cloud.google.com/go/storage.(*Writer).open.func1(0xc0000bcfc0, 0xc000220540, 0xc0000104b0, 0xc001330ce0, 0x1, 0x1)
	/home/dev/go/pkg/mod/cloud.google.com/go/storage@v1.1.2/writer.go:160 +0x77a
created by cloud.google.com/go/storage.(*Writer).open
	/home/dev/go/pkg/mod/cloud.google.com/go/storage@v1.1.2/writer.go:110 +0x3f3
```

go version go1.13 linux/amd64

google storage client  v1.1.2

**Comment by frankyn** [comment]
Hi @rntk and @kevinconaway,

Thanks for filing this issue, as you mentioned we saw the issue in #1385.

As we understand it now, it's an issue with how `io.Pipe` is used in the request body. This is being discussed in https://github.com/golang/go/issues/29246. 

I'm closing it here. Thank you for your patience.

**Comment by kevinconaway** [comment]
@frankyn Would you reconsider?  Based on my investigation, it looks like its not necessarily that `io.Pipe` is the problem its that the body isn't always being closed when `GetBody` is used which leaves the pipe reader dangling.

Its possible there is an issue with the implementation in `GetBody` that could be looked at here.
