### ISSUE TITLE
bigquery: put hangs on internal retry even with timeout

### ISSUE THREAD

**Issue by crazed** [googleapis/google-cloud-go#2216]
**Client**

bigquery at commit daaaf104253ac9d983c7fb656070270043560165 and google apis package at v0.16.0

**Environment**

CentOS 6 container on mesos, compiled with Go 1.13

**Code**

Client is setup in main using vanilla `bigquery.NewClient`, inserters are stored in a struct based on table names. Typically 2-3 goroutines for calling Put are created based on subscription to changes from 2-3 source tables.

e.g.
```go

// WriteChangesToInserters takes the provided changes and sends it to the provided inserter while
// converting the change to the bigquery.ValueSaver interface.
func WriteChangesToInserters(ctx context.Context, changes []*change.Change, config SourceConfig) error {
	// Create a map to batch changes by source for more efficient BQ inserts.
	// Also validate we have a corresponding Inserter while we are looping through changes.
	srcToChanges := map[Source][]*valueSaver{}
	for _, c := range changes {
		src := Source{Schema: c.Schema, Table: c.Table}
		if _, ok := config[src]; !ok {
			return errors.Wrapf(ErrUnknownTable, "no inserter for %s", src)
		}
		srcToChanges[src] = append(srcToChanges[src], &valueSaver{c, config[src].Converters})
	}

	// Perform BQ inserts concurrently as needed.
	var (
		wg      sync.WaitGroup
		errChan = make(chan error, len(srcToChanges))
	)
	for src, values := range srcToChanges {
		wg.Add(1)
		go func(ctx context.Context, inserter Inserter, values []*valueSaver, errChan chan<- error) {
			defer wg.Done()
			ctx, cancel := context.WithTimeout(ctx, time.Minute)
			defer cancel()
			if err := inserter.Put(ctx, values); err != nil {
				err = handleInsertError(err)
				logrus.WithError(err).WithFields(logrus.Fields{
					"value_count": len(values),
				}).Error("bigquery: failed to insert changes")
				errChan <- errors.Wrapf(err, "failed to insert changes")
			}
		}(ctx, config[src].Inserter, values, errChan)
	}
	wg.Wait()
	close(errChan)
	// return just the first error even if there are more, we are logging additional errors
	return <-errChan
}
```

**Expected behavior**

The `inserter.Put` call times  out after 1 minute of failure

**Actual behavior**

The `inserter.Put` call hangs for a long period of time, and eventually succeeds (takes up to 3 hours observed so far). 

**Additional context**

Here's a stack trace from the hanging goroutine:

```
goroutine 4217252 [select]:
net/http.(*http2ClientConn).roundTrip(0xc000ed0f00, 0xc00030cb00, 0x0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/bootstrap/bin/go/linux/x86_64/1.13/go.tar/go/src/net/http/h2_bundle.go:7573 +0x9a0
net/http.(*http2Transport).RoundTripOpt(0xc0001c8a80, 0xc00030cb00, 0xc000592a00, 0x6daea5, 0x0, 0xc0002feb40)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/bootstrap/bin/go/linux/x86_64/1.13/go.tar/go/src/net/http/h2_bundle.go:6936 +0x172
net/http.(*http2Transport).RoundTrip(...)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/bootstrap/bin/go/linux/x86_64/1.13/go.tar/go/src/net/http/h2_bundle.go:6897
net/http.http2noDialH2RoundTripper.RoundTrip(0xc0001c8a80, 0xc00030cb00, 0xc000496900, 0x5, 0xc0002febc8)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/bootstrap/bin/go/linux/x86_64/1.13/go.tar/go/src/net/http/h2_bundle.go:9032 +0x3e
net/http.(*Transport).roundTrip(0x14e5280, 0xc00030cb00, 0xb83c40, 0x14e5001, 0xc0009bc580)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/bootstrap/bin/go/linux/x86_64/1.13/go.tar/go/src/net/http/transport.go:485 +0xdc1
net/http.(*Transport).RoundTrip(0x14e5280, 0xc00030cb00, 0xcdf2bb, 0xa, 0xc0009bc620)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/bootstrap/bin/go/linux/x86_64/1.13/go.tar/go/src/net/http/roundtrip.go:17 +0x35
google.golang.org/api/transport/http.(*parameterTransport).RoundTrip(0xc000276780, 0xc00030ca00, 0x4, 0x4, 0xc000000000)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/google.golang.org/api/transport/http/dial.go:133 +0x224
go.opencensus.io/plugin/ochttp.(*traceTransport).RoundTrip(0xc000b02e00, 0xc00030ca00, 0xc0003a52e0, 0x1, 0x1)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/go.opencensus.io/plugin/ochttp/trace.go:73 +0x2e4
go.opencensus.io/plugin/ochttp.statsTransport.RoundTrip(0xde49e0, 0xc000b02e00, 0xc00030c800, 0xc000be6b50, 0xc000be6b50, 0xc16f80)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/go.opencensus.io/plugin/ochttp/client_stats.go:54 +0x41d
go.opencensus.io/plugin/ochttp.(*Transport).RoundTrip(0xc0002767c0, 0xc00030c800, 0xc00030c800, 0x0, 0xc0003b6380)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/go.opencensus.io/plugin/ochttp/client.go:89 +0x1fe
golang.org/x/oauth2.(*Transport).RoundTrip(0xc000271b30, 0xc00030c700, 0xc000271b30, 0x0, 0x0)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/golang.org/x/oauth2/transport.go:48 +0xcf
net/http.send(0xc00030c700, 0xde4a60, 0xc000271b30, 0x0, 0x0, 0x0, 0xc000010210, 0x75435e, 0x1, 0x0)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/bootstrap/bin/go/linux/x86_64/1.13/go.tar/go/src/net/http/client.go:250 +0x443
net/http.(*Client).send(0xc000271b60, 0xc00030c700, 0x0, 0x0, 0x0, 0xc000010210, 0x0, 0x1, 0x0)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/bootstrap/bin/go/linux/x86_64/1.13/go.tar/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc000271b60, 0xc00030c700, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/bootstrap/bin/go/linux/x86_64/1.13/go.tar/go/src/net/http/client.go:641 +0x3ce
net/http.(*Client).Do(...)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/bootstrap/bin/go/linux/x86_64/1.13/go.tar/go/src/net/http/client.go:509
google.golang.org/api/internal/gensupport.send(0xdf9880, 0xc0009b61e0, 0xc000271b60, 0xc00030c600, 0x15638c0, 0xc000593600, 0x756cf6)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/google.golang.org/api/internal/gensupport/send.go:67 +0xef
google.golang.org/api/internal/gensupport.SendRequest(0xdf9880, 0xc0009b61e0, 0xc000271b60, 0xc00030c600, 0xc0005938c0, 0x86, 0xde3e40)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/google.golang.org/api/internal/gensupport/send.go:52 +0x193
google.golang.org/api/bigquery/v2.(*TabledataInsertAllCall).doRequest(0xc000593c28, 0xcd9cb8, 0x4, 0x0, 0x0, 0xc0009a36f8)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/google.golang.org/api/bigquery/v2/bigquery-gen.go:10493 +0x8fc
google.golang.org/api/bigquery/v2.(*TabledataInsertAllCall).Do(0xc0008edc28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/google.golang.org/api/bigquery/v2/bigquery-gen.go:10505 +0xa8
cloud.google.com/go/bigquery.(*Inserter).putMulti.func1(0xc0003b6380, 0x7f00fdc5e1f0)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/cloud.google.com/go/bigquery/inserter.go:178 +0x44
cloud.google.com/go/bigquery.runWithRetry.func1(0x150, 0xc387c0, 0xc0008edb28)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/cloud.google.com/go/bigquery/bigquery.go:140 +0x2a
cloud.google.com/go/internal.retry(0xdf9880, 0xc0009b61e0, 0x3b9aca00, 0x773594000, 0x4000000000000000, 0x0, 0xc000593b38, 0xd12608, 0x10, 0xb83c40)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/cloud.google.com/go/internal/retry.go:38 +0x48
cloud.google.com/go/internal.Retry(...)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/cloud.google.com/go/internal/retry.go:31
cloud.google.com/go/bigquery.runWithRetry(0xdf9880, 0xc0009b61e0, 0xc0008edc10, 0x11, 0xc000b69ec8)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/cloud.google.com/go/bigquery/bigquery.go:139 +0x9f
cloud.google.com/go/bigquery.(*Inserter).putMulti(0xc0003a4280, 0xdf9880, 0xc0009b61e0, 0xc000cd8800, 0x64, 0x80, 0x0, 0xdf9880)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/cloud.google.com/go/bigquery/inserter.go:177 +0x354
cloud.google.com/go/bigquery.(*Inserter).Put(0xc0003a4280, 0xdf9840, 0xc000941500, 0xb68f60, 0xc0004a8f20, 0x0, 0x0)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/cloud.google.com/go/bigquery/inserter.go:96 +0x176
replication/sinks/bigquery.WriteChangesToInserters.func1(0xc0003da320, 0xdf9840, 0xc000941500, 0xde3fe0, 0xc0003a4280, 0xc00024d000, 0x64, 0x80, 0xc000941320)
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/replication/sinks/bigquery/change_inserter.go:48 +0x159
created by replication/sinks/bigquery.WriteChangesToInserters
	/var/lib/jenkins/jobs/pants_publish/workspace/.pants.d/binary/golang/src/replication/sinks/bigquery/change_inserter.go:44 +0x6a5
```

**Comment by shollyman** [comment]
Thanks for the report.  Trying to understand things a bit better here:

Are you doing anything with trace exports?  The inserter is instrumented with opencensus tracing, and I'd like to confirm there's not some interaction there that's not getting considered.

You mention there's 2-3 goroutines processing subscription changes.  Is that the typical number active at any time, or how many typically get created in response to mutations?  There was recently a change made to the underlying discovery clients to improve the connection pooling in response some queuing issues, but it's not clear if that's relevant here.  Do you have a lot of connections in flight interacting with the bigquery service (not necessarily just streaming inserts) when you observe this?

**Comment by crazed** [comment]
Ah I will turn on tracing for this application, we are using jaeger currently, did not realize the underlying packages were instrumented and this application does not currently have any custom tracing so we never turned it on.

As for number of goroutines, it depends on how many source tables are being processed. This stack trace is from a configuration that handles 5 tables, 3 of which are frequently updated, the other 2 are pretty static.

There are no other interactions with bigquery during this processing. I'll try to get more details, this also seems to have cleared up after changing the batch size to 500, so there are less network calls to bigquery itself.

**Comment by shollyman** [comment]
Closing this one for now as the last update seems to indicate the network/batching changes have helped here.  If this is incorrect or it resurfaces, please reopen.
