### ISSUE TITLE
bigtable: emulator crashes with concurrent operations

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-go#2600]
We never filed a bug for this, though we had plenty of communication with the emulator developers in googleapis/google-cloud-cpp#441.

The emulator crashes when performing concurrent operations. I think maybe SampleRowKeys combined with DropRowRange.

The first uses a lock to prevent problems:

https://github.com/googleapis/google-cloud-go/blob/fb3791807bf818c5c9d78d2c7e84303192d62de6/bigtable/bttest/inmem.go#L1064

The second does not seem to use the same lock:

https://github.com/googleapis/google-cloud-go/blob/fb3791807bf818c5c9d78d2c7e84303192d62de6/bigtable/bttest/inmem.go#L252-L287

That seems racy.

**Comment by dragonsinth** [comment]
Confirmed
https://github.com/googleapis/google-cloud-go/pull/4200

**Comment by coryan** [comment]
I think we need to reopen this:

```
Cloud Bigtable emulator running on 127.0.0.1:8480
fatal error: concurrent map iteration and map write

goroutine 13076 [running]:
runtime.throw(0x9ab765, 0x26)
        /usr/lib/google-golang/src/runtime/panic.go:623 +0x72 fp=0xc000925768 sp=0xc000925738 pc=0x42c3a2
runtime.mapiternext(0xc000925888)
        /usr/lib/google-golang/src/runtime/map.go:860 +0x597 fp=0xc0009257f0 sp=0xc000925768 pc=0x40ed87
cloud.google.com/go/bigtable/bttest.(*row).size(0xc00d15d900, 0x64)
        /usr/local/google/home/igorbernstein/go/pkg/mod/cloud.google.com/go/bigtable@v1.0.0/bttest/inmem.go:1312 +0x101 fp=0xc000925958 sp=0xc0009257f0 pc=0x865461
cloud.google.com/go/bigtable/bttest.(*server).SampleRowKeys.func1(0xa3ce80, 0xc00d15d900, 0xc008ebf701)
        /usr/local/google/home/igorbernstein/go/pkg/mod/cloud.google.com/go/bigtable@v1.0.0/bttest/inmem.go:1080 +0x99 fp=0xc0009259d8 sp=0xc000925958 pc=0x8677c9
github.com/google/btree.(*node).iterate(0xc009421b00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x100, 0xc000925c20, 0x101)
        /usr/local/google/home/igorbernstein/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:524 +0x52d fp=0xc000925a48 sp=0xc0009259d8 pc=0x5bafad
github.com/google/btree.(*node).iterate(0xc00999f080, 0x1, 0x0, 0x0, 0x0, 0x0, 0x100, 0xc000925c20, 0xc0000a0101)
        /usr/local/google/home/igorbernstein/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:512 +0x66b fp=0xc000925ab8 sp=0xc000925a48 pc=0x5bb0eb
github.com/google/btree.(*node).iterate(0xc00773de40, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc0002e0100, 0xc000925c20, 0xc000000101)
        /usr/local/google/home/igorbernstein/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:512 +0x66b fp=0xc000925b28 sp=0xc000925ab8 pc=0x5bb0eb
github.com/google/btree.(*node).iterate(0xc00773de80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000925c20, 0xc003f46b30)
        /usr/local/google/home/igorbernstein/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:512 +0x66b fp=0xc000925b98 sp=0xc000925b28 pc=0x5bb0eb
github.com/google/btree.(*BTree).Ascend(...)
        /usr/local/google/home/igorbernstein/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:777
cloud.google.com/go/bigtable/bttest.(*server).SampleRowKeys(0xc0001648c0, 0xc00a17dd40, 0xa4ce20, 0xc003f46b30, 0x0, 0x0)
        /usr/local/google/home/igorbernstein/go/pkg/mod/cloud.google.com/go/bigtable@v1.0.0/bttest/inmem.go:1068 +0x20c fp=0xc000925c68 sp=0xc000925b98 pc=0x86393c
google.golang.org/genproto/googleapis/bigtable/v2._Bigtable_SampleRowKeys_Handler(0x98e6a0, 0xc0001648c0, 0xa4bec0, 0xc012de8000, 0xe43010, 0xc00ade0000)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/genproto@v0.0.0-20190819201941-24fa4b261c55/googleapis/bigtable/v2/bigtable.pb.go:1355 +0x109 fp=0xc000925cc0 sp=0xc000925c68 pc=0x82ff09
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000001200, 0xa4db40, 0xc000329980, 0xc00ade0000, 0xc0001deed0, 0xe1a9a0, 0x0, 0x0, 0x0)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1202 +0xacd fp=0xc000925e50 sp=0xc000925cc0 pc=0x7f79bd
google.golang.org/grpc.(*Server).handleStream(0xc000001200, 0xa4db40, 0xc000329980, 0xc00ade0000, 0x0)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1282 +0xd3f fp=0xc000925f80 sp=0xc000925e50 pc=0x7f92df
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00ac62040, 0xc000001200, 0xa4db40, 0xc000329980, 0xc00ade0000)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0x9f fp=0xc000925fb8 sp=0xc000925f80 pc=0x80441f
runtime.goexit()
        /usr/lib/google-golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000925fc0 sp=0xc000925fb8 pc=0x457f71
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1

goroutine 1 [select (no cases)]:
main.main()
        /usr/local/google/home/igorbernstein/dev/cbt-go/src/cloud.google.com/go/bigtable/cmd/emulator/cbtemulator.go:51 +0x2f1

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7fc14a4f3f38, 0x72, 0x0)
        /usr/lib/google-golang/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000184318, 0x72, 0x0, 0x0, 0x99a13d)
        /usr/lib/google-golang/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/google-golang/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000184300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/google-golang/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc000184300, 0xc00ab40001, 0x0, 0x0)
        /usr/lib/google-golang/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000e0c0, 0xc000172ec0, 0xc000172ec8, 0x18)
        /usr/lib/google-golang/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000e0c0, 0x9bd440, 0xc000001200, 0xa4d540, 0xc00ab40000)
        /usr/lib/google-golang/src/net/tcpsock.go:260 +0x48
google.golang.org/grpc.(*Server).Serve(0xc000001200, 0xa485e0, 0xc00000e0c0, 0x0, 0x0)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:587 +0x1e9
created by cloud.google.com/go/bigtable/bttest.NewServer
        /usr/local/google/home/igorbernstein/go/pkg/mod/cloud.google.com/go/bigtable@v1.0.0/bttest/inmem.go:118 +0x2b9

goroutine 420 [runnable]:
cloud.google.com/go/bigtable/bttest.applyGC(0xc009535a00, 0x1, 0x1, 0xc000248e10, 0xc0049b6e50, 0x1, 0x1)
        /usr/local/google/home/igorbernstein/go/pkg/mod/cloud.google.com/go/bigtable@v1.0.0/bttest/inmem.go:1336 +0x4cf
cloud.google.com/go/bigtable/bttest.(*row).gc(0xc00d0e2380, 0xc0049b6d28)
        /usr/local/google/home/igorbernstein/go/pkg/mod/cloud.google.com/go/bigtable@v1.0.0/bttest/inmem.go:1303 +0x199
cloud.google.com/go/bigtable/bttest.(*table).gc.func1(0xa3ce80, 0xc00d0e2380, 0x8010101)
        /usr/local/google/home/igorbernstein/go/pkg/mod/cloud.google.com/go/bigtable@v1.0.0/bttest/inmem.go:1214 +0x6c
github.com/google/btree.(*node).iterate(0xc0095e7b80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x860100, 0xc0049b6d18, 0xc0049b0101)
        /usr/local/google/home/igorbernstein/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:524 +0x52d
github.com/google/btree.(*node).iterate(0xc00999f080, 0x1, 0x0, 0x0, 0x0, 0x0, 0x860100, 0xc0049b6d18, 0xc0049b0101)
        /usr/local/google/home/igorbernstein/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:512 +0x66b
github.com/google/btree.(*node).iterate(0xc00773de40, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc000290100, 0xc0049b6d18, 0xc000290101)
        /usr/local/google/home/igorbernstein/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:512 +0x66b
github.com/google/btree.(*node).iterate(0xc00773de80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x200000, 0xc0049b6d18, 0x2000)
        /usr/local/google/home/igorbernstein/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:512 +0x66b
github.com/google/btree.(*BTree).Ascend(...)
        /usr/local/google/home/igorbernstein/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:777
cloud.google.com/go/bigtable/bttest.(*table).gc(0xc000248e70)
        /usr/local/google/home/igorbernstein/go/pkg/mod/cloud.google.com/go/bigtable@v1.0.0/bttest/inmem.go:1211 +0x21d
cloud.google.com/go/bigtable/bttest.(*server).gcloop(0xc0001648c0, 0xc000768300)
        /usr/local/google/home/igorbernstein/go/pkg/mod/cloud.google.com/go/bigtable@v1.0.0/bttest/inmem.go:1120 +0x127
created by cloud.google.com/go/bigtable/bttest.(*server).needGC
        /usr/local/google/home/igorbernstein/go/pkg/mod/cloud.google.com/go/bigtable@v1.0.0/bttest/inmem.go:1092 +0xa2

goroutine 13073 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc00ac64040, 0x1, 0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/internal/transport/controlbuf.go:317 +0x104
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0100b8720, 0x0, 0x0)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/internal/transport/controlbuf.go:435 +0x1b6
google.golang.org/grpc/internal/transport.newHTTP2Server.func2(0xc000329980)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/internal/transport/http2_server.go:276 +0xcb
created by google.golang.org/grpc/internal/transport.newHTTP2Server
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/internal/transport/http2_server.go:273 +0xfba

goroutine 13075 [IO wait]:
internal/poll.runtime_pollWait(0x7fc14a4f34a8, 0x72, 0xffffffffffffffff)
        /usr/lib/google-golang/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00aa7e018, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
        /usr/lib/google-golang/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/google-golang/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00aa7e000, 0xc000582000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/lib/google-golang/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00aa7e000, 0xc000582000, 0x8000, 0x8000, 0x0, 0x400000801, 0x0)
        /usr/lib/google-golang/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00ab40000, 0xc000582000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/lib/google-golang/src/net/net.go:177 +0x69
bufio.(*Reader).Read(0xc01067e2a0, 0xc000958118, 0x9, 0x9, 0x18, 0x91bb00, 0x1)
        /usr/lib/google-golang/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0xa3cdc0, 0xc01067e2a0, 0xc000958118, 0x9, 0x9, 0x9, 0xc00ac62140, 0x500000000, 0xc007e2ddf0)
        /usr/lib/google-golang/src/io/io.go:310 +0x88
io.ReadFull(...)
        /usr/lib/google-golang/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc000958118, 0x9, 0x9, 0xa3cdc0, 0xc01067e2a0, 0x0, 0x0, 0xc00a95a040, 0xc00ac64050)
        /usr/local/google/home/igorbernstein/go/pkg/mod/golang.org/x/net@v0.0.0-20190620200207-3b0461eec859/http2/frame.go:237 +0x88
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0009580e0, 0xc00ac62130, 0xc00ac62130, 0x0, 0x0)
        /usr/local/google/home/igorbernstein/go/pkg/mod/golang.org/x/net@v0.0.0-20190620200207-3b0461eec859/http2/frame.go:492 +0xa1
google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc000329980, 0xc00a958180, 0x9bd4a0)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/internal/transport/http2_server.go:431 +0x7c
google.golang.org/grpc.(*Server).serveStreams(0xc000001200, 0xa4db40, 0xc000329980)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:713 +0xdd
google.golang.org/grpc.(*Server).handleRawConn.func1(0xc000001200, 0xa4db40, 0xc000329980)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:675 +0x43
created by google.golang.org/grpc.(*Server).handleRawConn
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:674 +0x580

goroutine 13074 [select]:
google.golang.org/grpc/internal/transport.(*http2Server).keepalive(0xc000329980)
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/internal/transport/http2_server.go:935 +0x1ed
created by google.golang.org/grpc/internal/transport.newHTTP2Server
        /usr/local/google/home/igorbernstein/go/pkg/mod/google.golang.org/grpc@v1.21.1/internal/transport/http2_server.go:282 +0xfdf

```

**Comment by coryan** [comment]
I think this might explain the problem... The GC loop is run asynchronously:

https://github.com/googleapis/google-cloud-go/blob/8f3275c8ca368c5d765bf66d3e3310f9300007f1/bigtable/bttest/inmem.go#L1149

This loop iterates over the rows, but only takes a read lock on the table, as the rows are not deleted:

https://github.com/googleapis/google-cloud-go/blob/8f3275c8ca368c5d765bf66d3e3310f9300007f1/bigtable/bttest/inmem.go#L1253-L1255

The rows are modified, and it takes a lock for them:

https://github.com/googleapis/google-cloud-go/blob/8f3275c8ca368c5d765bf66d3e3310f9300007f1/bigtable/bttest/inmem.go#L1268-L1273

However, `SampleRowKeys()` does not lock each row:

https://github.com/googleapis/google-cloud-go/blob/8f3275c8ca368c5d765bf66d3e3310f9300007f1/bigtable/bttest/inmem.go#L1125-L1140

**Comment by dragonsinth** [comment]
https://github.com/fullstorydev/emulators/blob/master/bigtable/bttest/inmem.go#L1378

In our fork, we just lock the table while doing GC, but yield the lock every 100 rows.  But we also do GC far less frequently.
