### ISSUE TITLE
Google Storage Golang API - invalid memory address or nil pointer dereference with Golang on Apple Silicone

### ISSUE THREAD

**Issue by qmilangowin** [googleapis/google-cloud-go#4567]
**Client**

e.g. Storage Golang API

**Environment**

Apple M1 (Silicone)

**Go Environment**

go version go1.16.7 darwin/arm64

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/milan-macbook-air/Library/Caches/go-build"
GOENV="/Users/milan-macbook-air/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/milan-macbook-air/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/milan-macbook-air/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/milan-macbook-air/Documents/Repos/PersonalProjects/ImageBox/server/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9f/tkx5m7v502zc2nwzxsgzh27m0000gn/T/go-build1463501949=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Code**

e.g.
```go
package main

func main() {
	// ...
}
```

**Expected behavior**

No fault, file is uploaded to bucket in GCP

**Actual behavior**

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x104fc3adc]

goroutine 32 [running]:
cloud.google.com/go/storage.(*Writer).open.func1(0x140003c2900, 0x1400023a3c0, 0x140001404d0, 0x140002fb9c0, 0x1, 0x1)
        /Users/milan-macbook-air/go/pkg/mod/cloud.google.com/go/storage@v1.16.0/writer.go:128 +0x9c
created by cloud.google.com/go/storage.(*Writer).open
        /Users/milan-macbook-air/go/pkg/mod/cloud.google.com/go/storage@v1.16.0/writer.go:118 +0x350

**Screenshots**

**Additional context**

This same code works fine on my other Macbook (Intel AMD chip) and GOARCH=amd64 but on my Apple Silicone Chip with GOARCH=arm64, the actual behaviour occurs.

No changes to the code.

**Comment by qmilangowin** [comment]
App wasn't authenticated. Issue fixed
