### ISSUE TITLE
internal/btree: BenchmarkFind fails with an interface assertion panic "panic: interface conversion: interface {} is btree.item, not int"

### ISSUE THREAD

**Issue by odeke-em** [googleapis/google-cloud-go#4941]
**Client**

internal

**Environment**

N/A

**Go Environment**

```shell
$ go version
go version devel go1.18-74e384f50d Fri Sep 17 19:32:44 2021 +0000 darwin/amd64
```

```shell
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/emmanuelodeke/go/bin"
GOCACHE="/Users/emmanuelodeke/Library/Caches/go-build"
GOENV="/Users/emmanuelodeke/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/emmanuelodeke/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/emmanuelodeke/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/emmanuelodeke/go/src/go.googlesource.com/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/emmanuelodeke/go/src/go.googlesource.com/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel go1.18-74e384f50d Fri Sep 17 19:32:44 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/emmanuelodeke/go/src/github.com/googleapis/google-cloud-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-build3167951879=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Expected behavior**

Benchmarks to pass

**Screenshots**

e.g. A chart showing how messages are slow. Delete if not necessary.
<img width="846" alt="Screen Shot 2021-10-03 at 10 51 29 PM" src="https://user-images.githubusercontent.com/4898263/135800583-3a42ba61-7893-409a-86bf-c64b19cd0303.png">

**Additional context**

Benchmarking fails with 
```shell
$ go test -run=^$ -bench=.
goos: darwin
goarch: amd64
pkg: cloud.google.com/go/internal/btree
cpu: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
BenchmarkInsert/degree=2-8             	 1888580	       626.6 ns/op
BenchmarkInsert/degree=8-8             	 3807860	       312.0 ns/op
BenchmarkInsert/degree=32-8            	 4741082	       248.0 ns/op
BenchmarkInsert/degree=64-8            	 4978332	       239.4 ns/op
BenchmarkDeleteInsert/degree=2-8       	  970608	      1179 ns/op
BenchmarkDeleteInsert/degree=8-8       	 2544859	       462.1 ns/op
BenchmarkDeleteInsert/degree=32-8      	 2732289	       432.6 ns/op
BenchmarkDeleteInsert/degree=64-8      	 2807827	       467.4 ns/op
BenchmarkDeleteInsertCloneOnce/degree=2-8         	 1033852	      1161 ns/op
BenchmarkDeleteInsertCloneOnce/degree=8-8         	 2598136	       462.3 ns/op
BenchmarkDeleteInsertCloneOnce/degree=32-8        	 2688867	       447.3 ns/op
BenchmarkDeleteInsertCloneOnce/degree=64-8        	 2803615	       436.0 ns/op
BenchmarkDeleteInsertCloneEachTime/degree=2-8     	  197304	      6044 ns/op
BenchmarkDeleteInsertCloneEachTime/degree=8-8     	  453591	      2628 ns/op
BenchmarkDeleteInsertCloneEachTime/degree=32-8    	  421459	      2877 ns/op
BenchmarkDeleteInsertCloneEachTime/degree=64-8    	  292816	      4045 ns/op
BenchmarkDelete/degree=2-8                        	 2453757	       485.6 ns/op
BenchmarkDelete/degree=8-8                        	 4217055	       281.8 ns/op
BenchmarkDelete/degree=32-8                       	 4629574	       252.8 ns/op
BenchmarkDelete/degree=64-8                       	 4851450	       245.1 ns/op
BenchmarkGet/degree=2-8                           	 3410487	       353.7 ns/op
BenchmarkGet/degree=8-8                           	 5324924	       223.1 ns/op
BenchmarkGet/degree=32-8                          	 5949234	       202.3 ns/op
BenchmarkGet/degree=64-8                          	 6130722	       197.0 ns/op
BenchmarkGetWithIndex/degree=2-8                  	 2966768	       405.5 ns/op
BenchmarkGetWithIndex/degree=8-8                  	 4653596	       255.1 ns/op
BenchmarkGetWithIndex/degree=32-8                 	 5041953	       239.0 ns/op
BenchmarkGetWithIndex/degree=64-8                 	 4973427	       231.2 ns/op
BenchmarkGetCloneEachTime/degree=2-8              	 2898501	       415.9 ns/op
BenchmarkGetCloneEachTime/degree=8-8              	 4045868	       299.0 ns/op
BenchmarkGetCloneEachTime/degree=32-8             	 4403460	       270.7 ns/op
BenchmarkGetCloneEachTime/degree=64-8             	 4814545	       252.5 ns/op
panic: interface conversion: interface {} is btree.item, not int

goroutine 75 [running]:
cloud.google.com/go/internal/btree.less(...)
	/Users/emmanuelodeke/go/src/github.com/googleapis/google-cloud-go/internal/btree/btree_test.go:411
cloud.google.com/go/internal/btree.findBinary({0x114a1a0, 0x12913a0}, {0xc000128100, 0x4, 0x31bfd70000195ef0})
	/Users/emmanuelodeke/go/src/github.com/googleapis/google-cloud-go/internal/btree/benchmarks_test.go:235 +0xa8
cloud.google.com/go/internal/btree.BenchmarkFind.func1.1(0xc0001406c0)
	/Users/emmanuelodeke/go/src/github.com/googleapis/google-cloud-go/internal/btree/benchmarks_test.go:223 +0x83
testing.(*B).runN(0xc0001406c0, 0x1)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/benchmark.go:192 +0x102
testing.(*B).run1.func1()
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/benchmark.go:232 +0x59
created by testing.(*B).run1
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/benchmark.go:225 +0x9c
exit status 2
FAIL	cloud.google.com/go/internal/btree	77.472s
```

/cc my colleagues for an FYI @cuonglm @kirbyquerby

**Comment by codyoss** [comment]
Thanks for pointing this out @odeke-em! Looking at this code I am not sure if this benchmark could have ever worked.

**Comment by odeke-em** [comment]
> Thanks for pointing this out @odeke-em! Looking at this code I am not sure if this benchmark could have ever worked.

Thanks for digging through and fixing it @codyoss! Yeah, if the benchmarks aren't run we'll have lots lurking in there and performance will regress without anyone knowing. That's why I shamelessly plug our product "Bencher" https://bencher.orijtech.com/ which will provide a GitHub check and it'll handle all the heavy lifting and ergonomics :-)
