### ISSUE TITLE
pubsub: Error trying to check topic exists on pubsub emulator

### ISSUE THREAD

**Issue by pbhavsarapplied** [googleapis/google-cloud-go#5117]
**Client**

PubSub

**Environment**

Alpine Docker on GKE

**Go Environment**

$ go version 1.17.1
$ go env

**Code**

e.g.
```go
import "cloud.google.com/go/pubsub"

func getTopic(ctx context.Context, client *pubsub.Client, topicName string) (*pubsub.Topic, error) {
	newTopic := client.Topic(topicName)

	// Create the topic if it doesn't exist.
	exists, err := newTopic.Exists(ctx)
	if err != nil {
		log.Fatal().Msgf("Error getting topic: %s\n", err)
		return nil, err
	}
	if !exists {
		fmt.Printf("Topic %v doesn't exist - creating it", topicName)
		newTopic, err = client.CreateTopic(ctx, topicName)
		if err != nil {
			log.Fatal().Msgf("Error creating topic: %s\n", err)
			return nil, err
		}
	}
	return newTopic, nil
}

func initiateTopicAndSubscriptions(ctx context.Context, config *configuration.PubsubConfig) (*pubsub.Topic, *pubsub.Topic, *pubsub.Subscription, *pubsub.Subscription, error) {
	client, err := pubsub.NewClient(ctx, config.ProjectID, option.WithoutAuthentication())

	if err != nil {
		log.Error().Msgf("error while creating new pubsub client - %v", err)
		return nil, nil, nil, nil, err
	}
	newMailEventTopic, err := getTopic(ctx, client, config.NewEmailEventTopic)
	if err != nil {
		log.Fatal().Msgf("Error getting topic %s: %s\n", config.NewEmailEventTopic, err)
		return nil, nil, nil, nil, err
	}
        //...

```

**Expected behavior**

I am having issue with using this package with pubsub emulator, ```exists, err := newTopic.Exists(ctx)``` line is returning error instead of bool value on whether topic exists or not

**Actual behavior**

When I checked logs for pubsub emulator I see following errors related to Unknown request URI not sure how package is creating URI path to be ```/google.pubsub.v1.Publisher/GetTopic```. I am sure PUBSUB_EMULATOR_HOST value is correct since I am seeing logs in pubsub emulator pod.
```
Executing: /root/google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=0.0.0.0 --port=8085
[pubsub] This is the Google Pub/Sub fake.
[pubsub] Implementation may be incomplete or differ from the real system.
[pubsub] Nov 11, 2021 8:25:17 PM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
[pubsub] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[pubsub] SLF4J: Defaulting to no-operation (NOP) logger implementation
[pubsub] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[pubsub] Nov 11, 2021 8:25:38 PM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: Server started, listening on 8085
[pubsub] Nov 11, 2021 8:25:39 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected non-HTTP/2 connection.
[pubsub] Nov 11, 2021 8:25:39 PM io.gapi.emulators.netty.NotFoundHandler handleRequest
[pubsub] INFO: Unknown request URI: /google.pubsub.v1.Publisher/GetTopic
[pubsub] Nov 11, 2021 8:25:41 PM io.gapi.emulators.netty.NotFoundHandler handleRequest
[pubsub] INFO: Unknown request URI: /google.pubsub.v1.Publisher/GetTopic
```

**Screenshots**

e.g. A chart showing how messages are slow. Delete if not necessary.

**Additional context**

e.g. Started after upgrading to v0.50.0.

**Comment by meredithslota** [comment]
cc'ing @kamalaboulhosn for discussion re: emulator functionality.

**Comment by hongalex** [comment]
Seems like the issue is related to this line `[pubsub] INFO: Detected non-HTTP/2 connection.`

I tried this just now and was able to establish an HTTP/2 connection:

```
Executing: /usr/local/share/google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=localhost --port=8043
[pubsub] This is the Google Pub/Sub fake.
[pubsub] Implementation may be incomplete or differ from the real system.
[pubsub] Feb 16, 2022 3:00:15 PM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
[pubsub] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[pubsub] SLF4J: Defaulting to no-operation (NOP) logger implementation
[pubsub] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[pubsub] Feb 16, 2022 3:00:16 PM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: Server started, listening on 8043
[pubsub] Feb 16, 2022 3:02:21 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected HTTP/2 connection.
[pubsub] Feb 16, 2022 3:04:28 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected HTTP/2 connection.
```

I suspect this is related to running the emulator in a separate pod, and this issue is with networking rather than the client library.

**Comment by icyflame** [comment]
I faced this issue inside GKE too. I was able to fix it by changing `.specs.ports[0].name` to `grpc-pubsub` from `http-pubsub`. My issue was related to Istio's Service Port naming conventions. As I had named the port with the prefix `http-`, Istio assumed that requests to the PubSub emulator were HTTP/2, when in fact, they were gRPC on HTTP/2. 

Here is a summary of how I fixed the problem.

### Setup

GKE with Istio service mesh sidecar for both pods. 

- 1 `Pod` is running the `gcloud pubsub emulator` on port 8085 (command: `gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project some-project-id`)
- Port 8085 of this pod is exposed using a `Service` called `pubsub-emulator`. Manifest below.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: pubsub-emulator
  namespace: namespace
spec:
  ports:
  - name: http-pubsub
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: application-pods
  type: ClusterIP
```
- 1 `Pod` is calling the emulator using the [`publisher.py`][publisherpy] Python script, which is mentioned in [PubSub's documentation][1]. The environment of this pod contains two variables:
    - `export PUBSUB_EMULATOR_HOST=pubsub-emulator.namespace.svc.cluster.local:8085`
    - `export PUBSUB_PROJECT_ID=some-project-id`

[1]: https://cloud.google.com/pubsub/docs/emulator#using_the_emulator
[publisherpy]: https://github.com/googleapis/python-pubsub/blob/c4ee2a1bfb9cc439f8e4a3fc72eab9f935d4573f/samples/snippets/publisher.py

### Behavior

I created a topic from the second pod using the following command:

```sh
$ python3 publisher.py some-project-id create some-topic-id
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 50, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "{"created":"@1655972527.200704877","description":"Error received from peer ipv4:10.162.25.189:8085","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Stream removed","grpc_status":2}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/python-pubsub/samples/snippets/publisher.py", line 488, in <module>
    create_topic(args.project_id, args.topic_id)
  File "/python-pubsub/samples/snippets/publisher.py", line 57, in create_topic
    topic = publisher.create_topic(request={"name": topic_path})
  File "/usr/lib/python3.10/site-packages/google/pubsub_v1/services/publisher/client.py", line 585, in create_topic
    response = rpc(
  File "/usr/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/usr/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/usr/lib/python3.10/site-packages/google/api_core/timeout.py", line 99, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 52, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.Unknown: None Stream removed
```

The logs on the PubSub Emulator were more helpful than this stacktrace:

```sh
[pubsub] Jun 23, 2022 8:22:07 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected non-HTTP/2 connection.
[pubsub] Jun 23, 2022 8:22:07 AM io.gapi.emulators.netty.NotFoundHandler handleRequest
[pubsub] INFO: Unknown request URI: /google.pubsub.v1.Publisher/CreateTopic
```

### Problem

Inside the Kubernetes `Service` `pubsub-emulator`, I had defined the name of the service port as `http-pubsub`. This port name causes Istio to believe that requests to this Service are HTTP requests.

> If you know the protocol the service port is serving, renaming the port with <protocol>[-<suffix>] format;
> -- https://istio.io/latest/docs/reference/config/analysis/ist0118/

The PubSub emulator uses gRPC to communicate. So, this is incorrect. The naming of this port caused Istio to treat the outgoing gRPC request as a HTTP/2 request.

### Resolution

Change the name of the service port to `grpc-pubsub` (the prefix `grpc-` is essential, it can be followed by any string).

This is the final Service manifest which worked for me:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: pubsub-emulator
  namespace: namespace
spec:
  ports:
  - name: grpc-pubsub
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: application-pods
  type: ClusterIP
```

### Behavior After Resolution

On the pod creating the topic:

```sh
$ python3 publisher.py some-project-id create some-topic-id
Created topic: projects/some-project-id/topics/some-topic-id
```


On the PubSub Emulator:

```sh
[pubsub] Jun 23, 2022 8:05:24 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected HTTP/2 connection.
```
