### ISSUE TITLE
pubsub: Mock Pubsub for unit testing

### ISSUE THREAD

**Issue by layla004** [googleapis/google-cloud-go#5458]
Hi, I am trying to unit test pubsub library using [gomock](https://pkg.go.dev/github.com/golang/mock/gomock), here is my code:

**pubsub.go**
```
func (ps *PubsubModule) PublishMessage(ctx context.Context, request *entity.Request) (msgId string, err error) {
	reqBodyBytes := new(bytes.Buffer)
	json.NewEncoder(reqBodyBytes).Encode(request)
        msg := &pubsub.Message{
		Data: []byte(reqBodyBytes.Bytes()),
	}

	topic := ps.PubsubClient.Topic("TOPIC_ID")
	res := topic.Publish(ctx, msg)
	msgID, err := res.Get(ctx)
	if err != nil {
		fmt.Println("ERROR")
		return "", err
	}
	return msgID, err
}
```

**pubsub_test.go**
```
func TestPubsubModule_PublishMessage(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	mockClient := NewMockClient(ctrl)

	topicAdapter := AdaptTopic(&pubsub.Topic{})
	request1 := &entity.Request{Email: "test@gmail.com",}

	type fields struct {
		PubsubCred    config.Auth
		PubsubClient  Client
	}
	type args struct {
		ctx        context.Context
		request    *entity.Request
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		wantErr bool
		patch   func()
	}{

		{
			name: "Success",
			fields: fields{
				PubsubCred:    config.Auth{ProjectID: "test",},
				PubsubClient:  mockClient,
			},
			args: args{
				ctx:        context.Background(),
				request: request1,
			},
			patch: func() {
				mockClient.EXPECT().Topic(gomock.Any()).Return(topicAdapter)
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ps := &PubsubModule{
				PubsubCred:    tt.fields.PubsubCred,
				PubsubClient:  tt.fields.PubsubClient,
			}
			tt.patch()
			_, err := ps.PublishMessage(tt.args.ctx, tt.args.request)
			if (err != nil) != tt.wantErr {
				t.Errorf("pubsub error = %v, wantErr %v", err, tt.wantErr)
				return
			}
		})
	}
}
```

**interfaces.go**
```
type (
	Client interface {
		Topic(id string) Topic
	}

	Topic interface {
		Publish(ctx context.Context, msg *pubsub.Message) PublishResult
	}

	PublishResult interface {
		Get(ctx context.Context) (serverID string, err error)
	}
)

type (
	client        struct{ *pubsub.Client }
	topic         struct{ *pubsub.Topic }
	publishResult struct{ *pubsub.PublishResult }
)

func (c client) Topic(id string) Topic {
	return topic{c.Client.Topic(id)}
}

func (t topic) Publish(ctx context.Context, msg *pubsub.Message) PublishResult {
	return publishResult{t.Topic.Publish(ctx, msg)}
}

func (r publishResult) Get(ctx context.Context) (serverID string, err error) {
	return r.PublishResult.Get(ctx)
}

func AdaptTopic(msg *pubsub.Topic) Topic {
	return topic{msg}
}
func AdaptClient(c *pubsub.Client) Client {
	return client{c}
}
```

but everytime I run the unit test, I always get this error: 

```
--- FAIL: TestPubsubModule_PublishMessage (0.00s)
    --- FAIL: TestPubsubModule_PublishMessage/Success (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15349ce]

goroutine 40 [running]:
testing.tRunner.func1.2(0x185fbe0, 0x1f53ee0)
	/usr/local/Cellar/go/1.16.4/libexec/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000001c80)
	/usr/local/Cellar/go/1.16.4/libexec/src/testing/testing.go:1146 +0x4b6
panic(0x185fbe0, 0x1f53ee0)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/panic.go:965 +0x1b9
cloud.google.com/go/pubsub.(*PublishResult).Get(0xc0001965d0, 0x0, 0x0, 0x28, 0xc0005ad2b0, 0x0, 0x0)
	/vendor/cloud.google.com/go/pubsub/topic.go:456 +0x4e
```
This error happens when reading this part of code:
`msgID, err := res.Get(ctx)` (in pubsub.go)

I don't know where did I go wrong, could anyone help or give other suggestions on how to mock google library? Thanks a bunch 😊

**Comment by codyoss** [comment]
From the stack trace you provided my guess would be something that should be initialized is not. What is line 456 in topic.go of the version of pubsub you pull in? That should be a good first step in debugging this. My guess is you need a little more mocking or some additional initialization. I don't believe this is an issue in the client itself though so I am closing this issue. Hope that helps point you in the right direction. As a side note, you may be interested in [pstest](https://pkg.go.dev/cloud.google.com/go/pubsub/pstest).
