### ISSUE TITLE
bigquery/storage: ManagedStream leaks goroutines & channels

### ISSUE THREAD

**Issue by fsaintjacques** [googleapis/google-cloud-go#6766]
**Client**

BigQuery/Storage

**Environment**

Any

**Go Environment**

Any

**Code**

There's a leak of goroutine & channel in managedwriter, here's a sample of goroutines after one of our services runs for a couple of hours. 

```
goroutine 659429 [chan receive, 3 minutes]:
cloud.google.com/go/bigquery/storage/managedwriter.recvProcessor({0x2576400, 0xc001a147e0}, {0x257cae8, 0xc002a2f1b0}, 0x4e52ea?, 0xc001b5f080)
	/home/circleci/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/storage/managedwriter/managed_stream.go:479 +0x3a6
created by cloud.google.com/go/bigquery/storage/managedwriter.(*ManagedStream).openWithRetry
	/home/circleci/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/storage/managedwriter/managed_stream.go:253 +0x3bc

goroutine 687101 [chan receive, 3 minutes]:
cloud.google.com/go/bigquery/storage/managedwriter.recvProcessor({0x2576400, 0xc001fc0db0}, {0x257cae8, 0xc001a1bad0}, 0xc0026be780?, 0xc002489a40)
	/home/circleci/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/storage/managedwriter/managed_stream.go:479 +0x3a6
created by cloud.google.com/go/bigquery/storage/managedwriter.(*ManagedStream).openWithRetry
	/home/circleci/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/storage/managedwriter/managed_stream.go:253 +0x3bc

goroutine 707842 [chan receive, 3 minutes]:
cloud.google.com/go/bigquery/storage/managedwriter.recvProcessor({0x2576400, 0xc0037f0870}, {0x257cae8, 0xc0016d79e0}, 0xc003213020?, 0xc0014a8840)
	/home/circleci/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/storage/managedwriter/managed_stream.go:479 +0x3a6
created by cloud.google.com/go/bigquery/storage/managedwriter.(*ManagedStream).openWithRetry
	/home/circleci/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/storage/managedwriter/managed_stream.go:253 +0x3bc

goroutine 108239 [chan receive, 11 minutes]:
cloud.google.com/go/bigquery/storage/managedwriter.recvProcessor({0x2576400, 0xc0018954d0}, {0x257cae8, 0xc0016c4f50}, 0x2576358?, 0xc0010bbf20)
	/home/circleci/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/storage/managedwriter/managed_stream.go:479 +0x3a6
created by cloud.google.com/go/bigquery/storage/managedwriter.(*ManagedStream).openWithRetry
	/home/circleci/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/storage/managedwriter/managed_stream.go:253 +0x3bc

goroutine 688691 [chan receive, 3 minutes]:
cloud.google.com/go/bigquery/storage/managedwriter.recvProcessor({0x2576400, 0xc003154990}, {0x257cae8, 0xc00309f290}, 0x94de26?, 0xc0030937a0)
	/home/circleci/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/storage/managedwriter/managed_stream.go:479 +0x3a6
created by cloud.google.com/go/bigquery/storage/managedwriter.(*ManagedStream).openWithRetry
	/home/circleci/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/storage/managedwriter/managed_stream.go:253 +0x3bc
```

**Comment by fsaintjacques** [comment]
Glancing at the code, it seems that the channel of writes is not closed and/or re-used when there's a reconnect, the leak would happen here https://github.com/googleapis/google-cloud-go/blob/main/bigquery/storage/managedwriter/managed_stream.go#L220

**Comment by shollyman** [comment]
Thanks for the report, will take a look.

**Comment by shollyman** [comment]
PR out to address this.
