### ISSUE TITLE
functions: UpdateFunctionOperation.Poll returns Invalid format of the operation name

### ISSUE THREAD

**Issue by Houndie** [googleapis/google-cloud-go#7154]
**Client**

e.g. Functions

**Environment**

Arch Linux

**Go Environment**

$ go version
`go version go1.19.3 linux/amd64`

$ go env
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jabenze/.cache/go-build"
GOENV="/home/jabenze/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jabenze/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jabenze/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jabenze/Projects/gcs_helper/tools/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3200449369=/tmp/go-build -gno-record-gcc-switches"
```

**Code**

e.g.
```go
// Relevant portion
   log.Info("kicking off build/deploy")
   operation, err := fclient.UpdateFunction(ctx, &functionspb.UpdateFunctionRequest{
      Function: &functionspb.Function{
         Name:        "projects/snip/locations/us-central1/functions/" + function,
         Environment: functionspb.Environment_GEN_2,
         BuildConfig: &functionspb.BuildConfig{
            Runtime:    "go116",
            EntryPoint: "HelloHTTP",
            Source: &functionspb.Source{
               Source: &functionspb.Source_StorageSource{
                  StorageSource: uploadURLResponse.StorageSource,
               },
            },
         },
      },
   })

   if err != nil {
      return fmt.Errorf("error updating function: %w", err)
   }

   log.Info("waiting for build/deploy")
   _, err = operation.Wait(ctx)
   if err != nil {
      return fmt.Errorf("error with function build/deploy: %w", err)
   }
```

**Expected behavior**

Program blocks on `operation.Wait()` until the update operation is completed

**Actual behavior**

The following error message is returned: 

```
error with function build/deploy: rpc error: code = InvalidArgument desc = The request has errors
error details: name = BadRequest field = name desc = Invalid format of the operation name.
```

**Additional context**

The update operation does go though, I can see the update happen successfully in the cloud console.  The issue seems to be purely with `Wait`'s ability to poll for it.

I tried putting a `Sleep` before it in case there was some kind of race, but that had no effect.

I am not super experienced with these libraries, it's entirely possible that there is user error here.

The contents of `operation.Name` are `projects/snip/locations/us-central1/operations/operation-1670679518390-5ef79633a2ac2-32c9b61a-64d6e33c` which seems legitimate to me?

**Comment by alsuren** [comment]
I reached this issue from a web search. I'm having the same behaviour with the nodejs equivalent, so I suspect it's a problem with the underlying API rather than any specific language bindings.

Workaround:

For now I'm applying labels to my function definition, and polling for completion by calling ```client.listFunctions({..., filter: `name = "${name}" AND labels.source_tree_hash = "${TREE_HASH}"`)``` if I want to know whether its status has changed.

<details><summary>js repro and log</summary>

```typescript
      const functionDescription = {
        name,
        labels: {
            source_changed_dt: LAST_CHANGED_DATE.replace(/[T:+]/g, "_"),
            source_tree_hash: TREE_HASH,
        },
        buildConfig: {
            runtime: "python39",
            source: {
                storageSource: {
                    bucket: "opvia-dev-scripts-sourcecode",
                    object: `scriptsV3-${LAST_CHANGED_DATE}-${TREE_HASH}.zip`,
                }
            },
            entryPoint: "hello_get",
        },
    }
// ...
        let [operation] = await client.updateFunction({
            function: functionDescription,
        })
        console.info("operation", operation)
        
        try {
            await operation.promise()
        } catch (e) {
            console.error(e.statusDetails[0].fieldViolations[0])
            throw e;
        }
```

```
operation Operation {
  _events: ...,
  _eventsCount: 2,
  _maxListeners: undefined,
  completeListeners: 0,
  hasActiveListeners: false,
  latestResponse: {
    name: 'projects/opvia-dev/locations/europe-west1/operations/operation-1671214350704-5eff5e9b7a05a-9f501e2e-66655b57',
    metadata: {
      type_url: 'type.googleapis.com/google.cloud.functions.v2.OperationMetadata',
      value: <Buffer ...>
    },
    done: false
  },
  name: 'projects/opvia-dev/locations/europe-west1/operations/operation-1671214350704-5eff5e9b7a05a-9f501e2e-66655b57',
  done: false,
  error: undefined,
  longrunningDescriptor: LongRunningDescriptor {
    operationsClient: OperationsClient {
      auth: [GoogleAuth],
      innerApiCalls: [Object],
      descriptor: [Object],
      operationsStub: [Promise]
    },
    responseDecoder: [Function: bound decode_setup],
    metadataDecoder: [Function: bound decode_setup]
  },
  result: null,
  metadata: OperationMetadata {
    stages: [],
    createTime: Timestamp { seconds: [Long], nanos: 328938300 },
    target: 'projects/opvia-dev/locations/europe-west1/functions/scripts-opvia-qa',
    verb: 'update',
    cancelRequested: false,
    apiVersion: 'v2'
  },
  backoffSettings: {
    initialRetryDelayMillis: 100,
    retryDelayMultiplier: 1.3,
    maxRetryDelayMillis: 60000,
    initialRpcTimeoutMillis: null,
    rpcTimeoutMultiplier: null,
    maxRpcTimeoutMillis: null,
    totalTimeoutMillis: null
  },
  _callOptions: CallSettings {
    timeout: 30000,
    retry: { retryCodes: [], backoffSettings: [Object] },
    autoPaginate: true,
    maxResults: undefined,
    otherArgs: { metadataBuilder: [Function: buildMetadata], headers: [Object] },
    bundleOptions: null,
    isBundling: true,
    longrunning: undefined,
    apiName: 'google.cloud.functions.v2.FunctionService',
    retryRequestOptions: undefined
  },
  [Symbol(kCapture)]: false
}
FieldViolation {
  field: 'name',
  description: 'Invalid format of the operation name.'
}
/Users/david/src/opvia/app/node_modules/@grpc/grpc-js/src/call.ts:81
  const error = new Error(message);
                ^
Error: 3 INVALID_ARGUMENT: The request has errors
    at Object.callErrorFromStatus (/Users/david/src/opvia/app/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/Users/david/src/opvia/app/node_modules/@grpc/grpc-js/src/client.ts:358:36)
    at Object.onReceiveStatus (/Users/david/src/opvia/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
    at Object.onReceiveStatus (/Users/david/src/opvia/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /Users/david/src/opvia/app/node_modules/@grpc/grpc-js/src/call-stream.ts:334:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/david/src/opvia/app/node_modules/@grpc/grpc-js/src/client.ts:328:30)
    at ServiceClientImpl.<anonymous> (/Users/david/src/opvia/app/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at /Users/david/src/opvia/app/node_modules/google-gax/src/operationsClient.ts:135:25
    at /Users/david/src/opvia/app/node_modules/google-gax/src/normalCalls/timeout.ts:54:13
    at OngoingCallPromise.call (/Users/david/src/opvia/app/node_modules/google-gax/src/call.ts:81:23)
    at NormalApiCaller.call (/Users/david/src/opvia/app/node_modules/google-gax/src/normalCalls/normalApiCaller.ts:43:15)
    at /Users/david/src/opvia/app/node_modules/google-gax/src/createApiCall.ts:118:26 {
  code: 3,
  details: 'The request has errors',
  metadata: Metadata {
    internalRepr: Map(2) {
      'google.rpc.badrequest-bin' => [Array],
      'grpc-status-details-bin' => [Array]
    },
    options: {}
  },
  statusDetails: [ BadRequest { fieldViolations: [Array] } ]
}
```
</details>

**Comment by codyoss** [comment]
Sorry we missed this issue last week. I am inclined to believe that this is indeed a backend API problem. If you have a support contract I would suggest reaching out through that or else I might recommend making an issue on the public issue tracker for this API: https://issuetracker.google.com/issues/new?component=187195&template=0

If you do create an issue for this please share the link for it after so other can follow the progress too.

**Comment by Houndie** [comment]
Thank you so much!  Will close this issue in favor of the API issue tracker:

https://issuetracker.google.com/issues/263283106
