### ISSUE TITLE
datastore: google.golang.org/appengine v1.6.7 => v2.0.3

### ISSUE THREAD

**Issue by trakhimenok** [googleapis/google-cloud-go#7760]
**Datastore**

**Environment**

AppEngine Standard

**Go Environment**

$ go version go1.20.2 darwin/arm64

**Code**

My project currently has next go.mod requirements:

```go
require cloud.google.com/go/datastore v1.11.0

require google.golang.org/appengine v1.6.7 // indirect
```

```terminal
$ go mod why google.golang.org/appengine
cloud.google.com/go/datastore
google.golang.org/api/transport/grpc
google.golang.org/appengine
```

**Expected behavior**

datastore refers to lates appenine - https://pkg.go.dev/google.golang.org/appengine/v2@v2.0.3

**Actual behavior**

Conflict when I try to use in my code appengine@v2:

```terminal
go test ./...
panic: proto: message remote_api.Request is already registered
See https://protobuf.dev/reference/go/faq#namespace-conflict


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x100e5a5c0?, 0x14000443250?}, {0x100e5a5c0?, 0x14000443250})
        /Users/alexandertrakhimenok/go/pkg/mod/google.golang.org/protobuf@v1.30.0/reflect/protoregistry/registry.go:56 +0x1fc
google.golang.org/protobuf/reflect/protoregistry.(*Types).register(0x1400009b230, {0x100bacd13, 0x7}, {0x100e66018, 0x1400052a380}, {0x100e44240?, 0x14000540000})
        /Users/alexandertrakhimenok/go/pkg/mod/google.golang.org/protobuf@v1.30.0/reflect/protoregistry/registry.go:579 +0x184
google.golang.org/protobuf/reflect/protoregistry.(*Types).RegisterMessage(0x1400009b230, {0x100e61890, 0x14000540000})
        /Users/alexandertrakhimenok/go/pkg/mod/google.golang.org/protobuf@v1.30.0/reflect/protoregistry/registry.go:506 +0xec
github.com/golang/protobuf/proto.RegisterType({0x100e61560?, 0x0}, {0x100bb54f5, 0x12})
        /Users/alexandertrakhimenok/go/pkg/mod/github.com/golang/protobuf@v1.5.3/proto/registry.go:181 +0x48
google.golang.org/appengine/v2/internal/remote_api.init.0()
        /Users/alexandertrakhimenok/go/pkg/mod/google.golang.org/appengine/v2@v2.0.2/internal/remote_api/remote_api.pb.go:315 +0x34
```

**Additional context**

`google.golang.org/appengine@v1` is not supported anymore:

- [Version: v1.6.7](https://pkg.go.dev/google.golang.org/appengine?tab=versions) Latest Published: **Oct 13, 2020**
- [Version: v2.0.3](https://pkg.go.dev/google.golang.org/appengine/v2@v2.0.3?tab=versions) Latest Published: Mar 27, 2023

**Comment by trakhimenok** [comment]
@telpirion , @bhshkh any chance this can be triaged any time soon and to get an ETA?

**Comment by trakhimenok** [comment]
@benguild here is the line in this module's go.mod that references obsolete library: https://github.com/googleapis/google-cloud-go/blob/e41aae26413fc0a31e2343c019b5c29a31efabc1/go.mod#L33

**Comment by dasper** [comment]
I am running into a similar issue upgrading a legacy AppEngine system to the new Standard 1.12+ instance. So many dependencies pull in appengine v1.6.7 if AppEngine is detected.

I am curious if you have any private repos or any replace statements in your go.mod file?

**Comment by benguild** [comment]
> @benguild here is the line in this module's go.mod that references obsolete library:
> 
> https://github.com/googleapis/google-cloud-go/blob/e41aae26413fc0a31e2343c019b5c29a31efabc1/go.mod#L33

Yes, indeed. Try diffing the non-indirect lines (not the indirect ones you referenced, which are generated automatically based on the required modules) one-by-one from your last working version... from most important to update, to least.

There are old versions of the packages that reference that one that should work.

I think this issue is caused (at least it was in the project I ran into it on) by another issue. It now works for me.

**Comment by dasper** [comment]
The issue I believe I am running into is related to the latest tag/master version of an included private module is still on legacy. Because of this, the go.mod file includes the appengine v1.6.7 as an indirect dependency because it thinks it is a dependency on a replaced module.

If this is the culprit then it gives a strange impasse on upgrading because even removing all appengine calls can still indirectly pull in v1.6.7 as cloud.google.com/go/datastore will include google.golang.org/api/transport/grpc which will include google.golang.org/appengine/socket which will cause the internal proto files which will case an error on compile on the standard environment.

Also, because of this, there is no older go.mod file to diff between as this is a new upgrade to support modules and attempting to update to modules on legacy does not work as there are many cloud modules which do not have a 1.11 module version to pull down.

Ideally, since the internal proto files being referenced are the exact same file, they should be updated to include appengine/v2 in the cloud repos or have the proto keys being registered changed so their is no conflict between them

**Comment by theory** [comment]
Seeing the same issue with

```
	cloud.google.com/go/bigquery v1.51.2
	google.golang.org/appengine/v2 v2.0.3
```

**Comment by codyoss** [comment]
The whole idea of goes module system is that multiple version may be imported at the same time. It seems like that is not possible with the appengine project here. I will reach out to some others about this.

**Comment by t-kitame** [comment]
FYI,  same issue with 
```
google.golang.org/api v0.117.0
google.golang.org/appengine/v2 v2.0.3
```
I think that it caused by s2a-go integration which has been added since v0.117.0

**Comment by benguild** [comment]
I ran into this on a random project just now, and was able to work around it by downgrading this package, and then tidying up `go.mod`:
```bash
go get google.golang.org/api@v0.116.0
```

Note that that seems to be that last version that does not have this issue, but YMMV... it's late here and I didn't spend a lot of time on this. 😅

**Comment by codyoss** [comment]
Sounds like this should be resolved yet this month, please see linked issue above.
