### ISSUE TITLE
logging: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ukai** [googleapis/google-cloud-go#8408]
**Client**

e.g. Cloud Logging

**Environment**

e.g. Alpine Docker on GKE

**Go Environment**

$ go version
$ go env

**Code**

https://chromium-review.googlesource.com/c/infra/infra/+/4769930/2/go/src/infra/go.mod

**Expected behavior**

Don't panic.

**Actual behavior**

https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8773108843220167633/+/u/Build_all_without_remote_cache/stdout

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xab79b8]

goroutine 177 [running]:
cloud.google.com/go/logging.(*loggerRetryer).Retry(0xc03d12d130, {0x1020d20, 0xc09477e630})
	cloud.google.com/go/logging@v1.8.0/logging.go:275 +0x78
github.com/googleapis/gax-go/v2.invoke({0x102b460, 0xc0992178f0}, 0xc0404e5e90, {0xc03d12d140, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0xdf8475800}, ...)
	github.com/googleapis/gax-go/v2@v2.12.0/invoke.go:108 +0x21d
github.com/googleapis/gax-go/v2.Invoke({0x102b460, 0xc0992178f0}, 0xc0404e5e70?, {0xc0847b7900, 0x3, 0xc099217830?})
	github.com/googleapis/gax-go/v2@v2.12.0/invoke.go:50 +0xdd
cloud.google.com/go/logging/apiv2.(*gRPCClient).WriteLogEntries(0xc000050540, {0x102b428?, 0xc099217830?}, 0xc055371420, {0xc03d12d160, 0x1, 0xc0404e5f10?})
	cloud.google.com/go/logging@v1.8.0/apiv2/logging_client.go:360 +0x192
cloud.google.com/go/logging/apiv2.(*Client).WriteLogEntries(...)
	cloud.google.com/go/logging@v1.8.0/apiv2/logging_client.go:225
cloud.google.com/go/logging.(*Logger).writeLogEntries(0xc000720c00, {0xc03221b800, 0x3e8, 0x500})
	cloud.google.com/go/logging@v1.8.0/logging.go:738 +0x23b
cloud.google.com/go/logging.(*Client).Logger.func2({0xd15ec0?, 0xc07f8d21f8?})
	cloud.google.com/go/logging@v1.8.0/logging.go:298 +0x45
google.golang.org/api/support/bundler.(*Bundler).handle(0xc0000ea420, 0x0?)
	google.golang.org/api@v0.136.0/support/bundler/bundler.go:324 +0x4a
created by google.golang.org/api/support/bundler.(*Bundler).enqueueCurBundle
	google.golang.org/api@v0.136.0/support/bundler/bundler.go:179 +0x14d
```

**Additional context**

Started after upgrading to v1.8.0

**Comment by noi** [comment]
I have encountered the same problem. I think the cause is that `defaultRetryer` is always nil.

- https://github.com/googleapis/google-cloud-go/blob/1de0374ff74b0d782b33b9672a33d619f4d8c9fa/logging/logging.go#L267-L276
- https://github.com/googleapis/google-cloud-go/blob/1de0374ff74b0d782b33b9672a33d619f4d8c9fa/logging/logging.go#L737

**Comment by noahdietz** [comment]
I've got what I think is the proper fix in #8415 but will need @daniel-sanche or @tomo241 to verify/review.

**Comment by noahdietz** [comment]
Reopening until I release the fix.

**Comment by noahdietz** [comment]
Please give this new patch release a shot!
